/*
  # Create reviews table

  1. New Tables
    - `reviews`
      - `id` (bigint, primary key)
      - `created_at` (timestamp with time zone)
      - `name` (text)
      - `content` (text)
      - `rating` (integer)
  2. Security
    - Enable RLS on `reviews` table
    - Add policies for anonymous users to read all reviews
    - Add policies for anonymous users to insert new reviews
*/

CREATE TABLE IF NOT EXISTS reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name text NOT NULL,
  content text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5)
);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read reviews"
  ON reviews
  FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Anyone can insert reviews"
  ON reviews
  FOR INSERT
  TO anon
  WITH CHECK (true);