/*
  # Create recipe photos table and storage

  1. New Tables
    - `recipe_photos`
      - `id` (bigint, primary key)
      - `created_at` (timestamp with time zone)
      - `title` (text, optional title for the recipe)
      - `image_url` (text, URL of the uploaded image)
      - `display_order` (integer, for ordering photos in slideshow)

  2. Security
    - Enable RLS on `recipe_photos` table
    - Add policy for anonymous users to read all recipe photos
    - Add policy for authenticated users to insert new recipe photos
    - Add policy for authenticated users to update recipe photos
    - Add policy for authenticated users to delete recipe photos

  3. Storage
    - Create storage bucket for recipe photos (to be done manually in Supabase dashboard)
*/

CREATE TABLE IF NOT EXISTS recipe_photos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  title text,
  image_url text NOT NULL,
  display_order integer DEFAULT 0
);

ALTER TABLE recipe_photos ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read recipe photos
CREATE POLICY "Anyone can read recipe photos"
  ON recipe_photos
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- Allow authenticated users to insert recipe photos
CREATE POLICY "Authenticated users can insert recipe photos"
  ON recipe_photos
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Allow authenticated users to update recipe photos
CREATE POLICY "Authenticated users can update recipe photos"
  ON recipe_photos
  FOR UPDATE
  TO authenticated
  USING (true);

-- Allow authenticated users to delete recipe photos
CREATE POLICY "Authenticated users can delete recipe photos"
  ON recipe_photos
  FOR DELETE
  TO authenticated
  USING (true);